[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

# Zama FHE specific configuration
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"

# Etherscan/Blockscout verification config is optional. Disabled for Lisk Sepolia by default.
# To enable later, add the proper Blockscout API URL for chain 4202:
# [etherscan]
# 4202 = { key = "${ETHERSCAN_API_KEY}", url = "https://<lisk-sepolia-blockscout-domain>/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
