export const fheAuctionAbi = [
  {
    type: 'function',
    name: 'getAuctionInfo',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'seller', type: 'address' },
      { name: 'assetType', type: 'uint8' },
      { name: 'assetContract', type: 'address' },
      { name: 'tokenId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'startTime', type: 'uint256' },
      { name: 'biddingEndTime', type: 'uint256' },
      { name: 'revealEndTime', type: 'uint256' },
      { name: 'phase', type: 'uint8' },
    ],
  },
  {
    type: 'function',
    name: 'startBidding',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'placeBid',
    stateMutability: 'payable',
    inputs: [
      { name: '_bidPlain', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'transitionToReveal',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revealBid',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalizeAuction',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getBidderCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [ { name: '', type: 'uint256' } ],
  },
  {
    type: 'function',
    name: 'bids',
    stateMutability: 'view',
    inputs: [ { name: '', type: 'address' } ],
    outputs: [
      { name: 'bidder', type: 'address' },
      { name: 'encryptedAmount', type: 'bytes32' },
      { name: 'isRevealed', type: 'bool' },
      { name: 'depositAmount', type: 'uint256' },
    ],
  },
] as const;
